services:
  backend:
    build:
      context: .  
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    env_file:
      - backend/.env
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build: ./frontend
    ports:
      - "4173:4173"
    depends_on:
      - backend

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    env_file:
      - backend/.env

volumes:
  mongo_data:
